default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doitnow_development

test:
  <<: *default
  database: doitnow_test

production:
  <<: *default
  database: doitnow_production
  username: doitnow
  password: <%= ENV['doitnow_DATABASE_PASSWORD'] %>
